In [2]:
import numpy as np

In [4]:
a=np.array([1,4,6,9])
print("1D array is : ",a)
b=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print("2D array is : ",b)


1D array is :  [1 4 6 9]
2D array is :  [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


# PYTHON LISTS vs NUMPY ARRAYS

In [5]:
py_lists=[1,3,5,7,9]
print("The list multiplied by 2 is : ",py_lists*2)

numpy_array=np.array([1,3,5,7,9])
print("The array multiplied by 2 is : ",numpy_array*2)  #Element wise multiplication

The list multiplied by 2 is :  [1, 3, 5, 7, 9, 1, 3, 5, 7, 9]
The array multiplied by 2 is :  [ 2  6 10 14 18]


In [8]:
import time

start=time.time()

py_list= [i*2 for i in  range (1000000)]
print("The time taken by list is : ",time.time()-start)

start=time.time()
numpy_array=np.arange(100000)
print("The time taken by array is : ",time.time()-start)

#See the numpy is faster....



The time taken by list is :  0.1153709888458252
The time taken by array is :  0.0003268718719482422


# CREATING ARRAYS FROM SCRATCH

In [9]:
zero=np.zeros((4,5))
print(zero)    #array with all zeros of 4 rows and 5 columns

one=np.ones((4,5))
print(one)      #array with all ones of 4 rows and 5 columns

full=np.full((10,9),16)
print(full) #array with all 16s of 10 rows and 9 columns

random=np.random.random((100,99))
print(random)  #array with random numbers of 100 rows and 99 columns..
 
sequence=np.arange(2,100000,2)   #Start , Stop , Step
print(sequence)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16]]
[[0.17030776 0.1000471  0.27970477 ... 0.48438851 0.06696241 0.88353751]
 [0.66617627 0.70164236 0.75827505 ... 0.15019575 0.50954706 0.23707206]
 [0.75512928 0.44927521 0.1639     ... 0.10260511 0.45824452 0.74655727]
 ...
 [0.33895269 0.75566011 0.35599626 ... 0.21712715 0.67595149 0.2481625 ]
 [0.06455988 0.86898315 0.37934366 ... 0.62053118 0.41637965 0.84598104]
 [0.75276893 0.81454806 0.51227918 ... 0.44168578 0.51007866 0.53933906]]
[    2     4     6 ... 99994 99996 99998]


# VECTOR , MATRIX AND TENSOR

In [ ]:
vector=np.array([1,2,3,4,5,6])
print("A vector is : ",vector)

matrix=np.array([[1,2,3,4],
                 [2,4,5,6]])
print("A matrix is : ",matrix)

tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("A tensor is : ",tensor)


A vector is :  [1 2 3 4 5 6]
A matrix is :  [[1 2 3 4]
 [2 4 5 6]]
A tensor is :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# ARRAY PROPERTIES

In [12]:
a=np.array([[1,2,3],
            [4,5,6]])

print("Shape is : ",a.shape) # Rows and columns
print("Dimensions : ",a.ndim) #Dimensions
print("Size : ",a.size) #No. of elements
print("Datatype : ",a.dtype)

Shape is :  (2, 3)
Dimensions :  2
Size :  6
Datatype :  int64


# ARRAY RERSHAPING

In [13]:
a=np.arange(16)
print("Original array : ",a)

reshaped=a.reshape((2,8)) # Product of rows and columns given should be equal to number of elements
print("Reshaped array : ",reshaped)

flattened=reshaped.flatten()
print("Flattened array : ",flattened)

raveled=reshaped.ravel()      #Returns a view(whenever possible) , instead of copy like flattened
print("Ravelled array : ",raveled)

transpose=reshaped.T
print("Transposed array : ",transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array :  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Ravelled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Transposed array :  [[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]
