# Creating Arrays from Scratch:

In [1]:
import numpy as np

In [3]:
arr1=np.zeros((12,34))   #  12x34 array of zeros
print(arr1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [4]:
arr2=np.ones((3,5)) # 3x5 array of ones
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
arr3=np.full((3,3),10)  # 3x3 array filled with 10
print (arr3)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
arr4=np.eye(5)  #  5x5 identity matrix
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
arr5=np.arange(4,45,2)   # (like range) (start,stop,jump)
print(arr5)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44]


In [ ]:
arr6=np.linspace(0, 12, 5) # 5 elements from 0 to 12 equally spaces
print(arr6)

# Checking Array Properties

In [11]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(myarr.shape)  # (rows,columns)

print(myarr.size)  # No. of elements

print(myarr.ndim)  # Dimensions

print(myarr.dtype)   #data type
 

(3, 3)
9
2
int64


In [20]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float16')   # Explicitly
print(myarr.dtype)  

float16


In [22]:
int_arr=myarr.astype('int32')   # Converting float to int
print(int_arr.dtype)

int32


# Reshaping and Flattening Arrays

In [23]:
mylife=np.array([[1,2,3],[7,8,9],[1,4,6]])
print(mylife.shape)

(3, 3)


In [25]:
reshaped=mylife.reshape(9,1)
print(reshaped)     #rows * columns * (other dims if any) must stay the same before and after reshaping.
print(reshaped.shape)

[[1]
 [2]
 [3]
 [7]
 [8]
 [9]
 [1]
 [4]
 [6]]
(9, 1)


In [26]:
flattened=mylife.flatten()
print(flattened)
print(flattened.shape)

[1 2 3 7 8 9 1 4 6]
(9,)


In [30]:
transpose=mylife.T  # Gives transpose
print(transpose)

[[1 7 1]
 [2 8 4]
 [3 9 6]]
