In [1]:
import numpy as np

In [2]:


marks = np.array([  
    [78, 85, 62, 90, 88],  
    [92, 76, 81, 95, 89],  
    [65, 70, 58, 60, 72],  
    [88, 90, 92, 85, 91],  
    [55, 60, 65, 70, 75],  
    [99, 95, 100, 98, 97],  
    [80, 82, 78, 85, 88],  
    [72, 68, 74, 70, 65],  
    [91, 89, 85, 87, 90],  
    [60, 65, 55, 58, 62]  
])

### MEAN MARKS PER SUBJECT

In [5]:
for i in range(5):
    
        print("Mean in subject is : ",np.mean(marks[:,i],axis=0))


Mean in subject is :  78.0
Mean in subject is :  78.0
Mean in subject is :  75.0
Mean in subject is :  79.8
Mean in subject is :  81.7


### HIGHEST MARKS PER STUDENT

In [8]:
for i in range(10):
    print(f"Student {i+1} highest mark: {np.max(marks[i])}")


Student 1 highest mark: 90
Student 2 highest mark: 95
Student 3 highest mark: 72
Student 4 highest mark: 92
Student 5 highest mark: 75
Student 6 highest mark: 100
Student 7 highest mark: 88
Student 8 highest mark: 74
Student 9 highest mark: 91
Student 10 highest mark: 65


### STUDENT WITH HIGHEST MARKS

In [ ]:
totals = np.sum(marks, axis=1)
topper_index = np.argmax(totals) #Tells us index of highest total marks
print(f"Student with highest total marks is student number {topper_index+1} with total marks {totals[topper_index]}.")


Student with highest total marks is student number 6 with total marks 489.


### SUBJECT WITH LOWEST AVERAGE

In [13]:
average=np.mean(marks,axis=0)
index=np.argmin(average)

print(f'The subject {index+1} has least average of {average[index]} amongst all. Please change that stupid professor!!')

The subject 3 has least average of 75.0 amongst all. Please change that stupid professor!!


### STANDARD DEVIATION OF MARKS

In [ ]:
print(f'The standard deviation of marks is {np.std(marks,axis=0)}')


#It tells us how the values are scattered wrt average.. if standard deviation small , values are clustured near average otherwise values are scattered away from average.
#Subject 5 is more consistent as many students are getting marks near average as std value is small


The standard deviation of marks is [14.02854233 11.3137085  14.20563269 13.53366174 11.52432211]


### students scored above 90 in at least one subject

In [ ]:

above_90_any = np.any(marks > 90, axis=1) ## Boolean array: True if student scored >90 in any subject


count = np.sum(above_90_any)

print(f"Total {count} students scored above 90 in at least one subject")

## Create a boolean array where True indicates a student scored >90 in a subject
# np.any(..., axis=1) collapses each row to a single True/False:
#   True → student scored >90 in at least one subject
#   False → student didn't score >90 in any subject
# np.sum(...) then counts how many students have at least one True



Total 4 students scored above 90 in at least one subject


### SORTED MARKS PER STUDENT

In [24]:
sorted=np.sort(marks,axis=1)
print(sorted)

[[ 62  78  85  88  90]
 [ 76  81  89  92  95]
 [ 58  60  65  70  72]
 [ 85  88  90  91  92]
 [ 55  60  65  70  75]
 [ 95  97  98  99 100]
 [ 78  80  82  85  88]
 [ 65  68  70  72  74]
 [ 85  87  89  90  91]
 [ 55  58  60  62  65]]


### OVERALL CLASS AVERAGE

In [25]:
print(f"Overall class average is {np.mean(marks)}")

Overall class average is 78.5


### LOWEST MARKS INDEX

In [ ]:
# Find the index of the minimum mark in the flattened array
min_index_flat = np.argmin(marks)

# Convert flattened index to (row, column)
row, col = np.unravel_index(min_index_flat, marks.shape)

print(f"The lowest mark is {marks[row, col]} of student {row+1} in subject {col+1}")

The lowest mark is 55 of student 5 in subject 1


### NORMALISE

In [ ]:
#xnorm​=x-xmin/xmax−xmin​​ in formula to make all marks cocelead in range 0 to 1... with 1 being assigned to highest value and 0 to minimun value

In [32]:
max_marks=np.max(marks)
min_marks=np.min(marks)

normalise_marks= (marks-min_marks)/(max_marks-min_marks)
print(normalise_marks)

[[0.51111111 0.66666667 0.15555556 0.77777778 0.73333333]
 [0.82222222 0.46666667 0.57777778 0.88888889 0.75555556]
 [0.22222222 0.33333333 0.06666667 0.11111111 0.37777778]
 [0.73333333 0.77777778 0.82222222 0.66666667 0.8       ]
 [0.         0.11111111 0.22222222 0.33333333 0.44444444]
 [0.97777778 0.88888889 1.         0.95555556 0.93333333]
 [0.55555556 0.6        0.51111111 0.66666667 0.73333333]
 [0.37777778 0.28888889 0.42222222 0.33333333 0.22222222]
 [0.8        0.75555556 0.66666667 0.71111111 0.77777778]
 [0.11111111 0.22222222 0.         0.06666667 0.15555556]]
