In [1]:
import numpy as np

In [2]:
sales = np.array([
    [120, 135, 150, 160, 145, 155, 170],  # Product A
    [80, 90, 85, 88, 92, 95, 100],        # Product B
    [60, 65, 70, 75, 68, 72, 74],         # Product C
    [200, 210, 190, 205, 198, 215, 220],  # Product D
    [50, 55, 45, 60, 52, 58, 65],         # Product E
    [130, 140, 135, 145, 150, 155, 160]   # Product F
])

### AVERAGE PER PRODUCT

In [ ]:
print("Average per product is : ",np.mean(sales,axis=1))

Average per product is :  [147.85714286  90.          69.14285714 205.42857143  55.
 145.        ]


### TOTAL SALES PER DAY

In [4]:
print("Total sale per day are : ",np.sum(sales,axis=0))

Total sale per day are :  [640 695 675 733 705 750 789]


### PRODUCT WITH HIGHEST WEEKLY SALES

In [6]:
total=np.sum(sales,axis=1)
product_max=np.argmax(total)
print(f"The product {product_max+1} has highest weekly sale which is {total[product_max]}")

The product 4 has highest weekly sale which is 1438


### LOWEST TOTAL SALE

In [8]:

lowest = np.min(sales)
row, col = np.where(sales == lowest)  # returns arrays
print(f"The day with lowest sales is day {col[0]+1} of product {row[0]+1} which is {lowest}")


The day with lowest sales is day 3 of product 5 which is 45


### PRODUCT WITH MOST CONSISTENT SALES

In [10]:
deviation=np.std(sales,axis=1)
most_consistent=np.argmin(deviation)

print(f"The product {most_consistent+1} was most consistent in sales")


The product 3 was most consistent in sales


### how many products had any day with sales >200.

In [11]:
sales=np.any(sales>200,axis=1)
count=np.sum(sales)

print(count)

1


### NORMALISE SALES PER PRODUCT

In [19]:
sales_max = np.max(sales)
sales_min = np.min(sales)

normal_sales = (sales - sales_min) / (sales_max - sales_min)
print(normal_sales)


[[0.42857143 0.51428571 0.6        0.65714286 0.57142857 0.62857143
  0.71428571]
 [0.2        0.25714286 0.22857143 0.24571429 0.26857143 0.28571429
  0.31428571]
 [0.08571429 0.11428571 0.14285714 0.17142857 0.13142857 0.15428571
  0.16571429]
 [0.88571429 0.94285714 0.82857143 0.91428571 0.87428571 0.97142857
  1.        ]
 [0.02857143 0.05714286 0.         0.08571429 0.04       0.07428571
  0.11428571]
 [0.48571429 0.54285714 0.51428571 0.57142857 0.6        0.62857143
  0.65714286]]


### OVERALL SALES OF THE WEEK

In [20]:
overall_sales_week=np.sum(sales,axis=1)
print(overall_sales_week)

[1035  630  484 1438  385 1015]


### MAXIMUM SALE

In [23]:
max_sale = np.max(sales)
rows, columns = np.where(sales == max_sale)

print(f"The product {rows[0]+1} has maximum sale on day {columns[0]+1} which is {max_sale}")


The product 4 has maximum sale on day 7 which is 220


### SORT DAYWISE FOR EACH PRODUCT

In [3]:
sorted=np.sort(sales,axis=1)
print(sorted)

[[120 135 145 150 155 160 170]
 [ 80  85  88  90  92  95 100]
 [ 60  65  68  70  72  74  75]
 [190 198 200 205 210 215 220]
 [ 45  50  52  55  58  60  65]
 [130 135 140 145 150 155 160]]
