In [1]:
import numpy as np

# Seed for reproducibility
np.random.seed(101)

# Big array: 100 rows, 6 columns
# Columns: Age, BMI, Blood Pressure, Glucose, Insulin, Outcome (0/1)
data = np.random.randint(20, 80, size=(100, 1))   # Age 20-79
bmi = np.random.randint(15, 40, size=(100, 1))    # BMI 15-39
bp = np.random.randint(80, 160, size=(100, 1))    # Blood Pressure 80-159
glucose = np.random.randint(70, 200, size=(100, 1)) # Glucose 70-199
insulin = np.random.randint(15, 276, size=(100, 1)) # Insulin 15-275
outcome = np.random.randint(0, 2, size=(100, 1))    # 0 or 1

# Stack them horizontally
data = np.hstack((data, bmi, bp, glucose, insulin, outcome))

print("Shape of data:", data.shape)
print("First 5 rows:\n", data[:5])


Shape of data: (100, 6)
First 5 rows:
 [[ 51  33 137  71 236   1]
 [ 31  30 103 140 180   0]
 [ 37  26 106 115 102   0]
 [ 26  25 156 166 168   0]
 [ 43  32 146 149 215   1]]


In [2]:
print(data)

[[ 51  33 137  71 236   1]
 [ 31  30 103 140 180   0]
 [ 37  26 106 115 102   0]
 [ 26  25 156 166 168   0]
 [ 43  32 146 149 215   1]
 [ 31  18 134 157 230   0]
 [ 67  18  97  92  80   0]
 [ 29  34 145 164 266   0]
 [ 33  35 137 116  85   0]
 [ 60  30  82 141 176   0]
 [ 24  29 130 111 171   0]
 [ 60  20 146  86 159   1]
 [ 73  20 159 157  64   0]
 [ 48  39  86 196 184   1]
 [ 20  34 122 141  26   0]
 [ 66  21 102  79 158   0]
 [ 25  39 100 191 106   0]
 [ 32  22 105 173  34   0]
 [ 49  20 134 158 220   0]
 [ 60  29 151 146 127   0]
 [ 69  22 152 163 230   1]
 [ 39  20 144 179  85   1]
 [ 67  19 143 122 148   1]
 [ 78  35 118  77 274   1]
 [ 28  38 125 183 120   1]
 [ 71  18 115 143 270   0]
 [ 49  30 105 156  41   0]
 [ 71  17 155  84 239   0]
 [ 79  18 152 119 230   1]
 [ 54  33  91 167 110   1]
 [ 64  28 156 110 174   1]
 [ 28  29 159  87 103   0]
 [ 77  18 130 192  72   1]
 [ 39  29 102 167 174   1]
 [ 30  20 139 192  50   0]
 [ 32  37 146  83 264   1]
 [ 51  37  81  85 251   0]
 

## Compute the mean, median, and standard deviation of BMI and Glucose.

In [5]:
bmi=data[:,1]
glucose=data[:,3]

mean1=np.mean(bmi)
mean2=np.mean(glucose)

sd1=np.std(bmi)
sd2=np.std(glucose)

print(mean1)
print(mean2)
print(sd1)
print(sd2)

27.93
139.17
7.140385143673974
35.03542635676067


## How many diabetics (Outcome = 1) have Blood Pressure > 120?

In [6]:
bp=data[:,2]

high= bp>120

print(np.size(bp[high]))

55


## Find the 25th, 50th, and 75th percentiles of Age

In [7]:
age=data[:,0]

print(np.percentile(age,25))
print(np.percentile(age,50))
print(np.percentile(age,75))

32.0
49.5
66.0


## Which row has the maximum Glucose value? What are all the feature values of that person?

In [10]:
print(np.argmax(glucose))

print(data[np.argmax(glucose)])

77
[ 39  18 109 197 231   0]


## Normalize the columns Age, BMI, and Blood Pressure to a [0,1] scale using Min-Max normalization.

In [12]:
# Columns: Age=0, BMI=1, BP=2
cols_to_norm = data[:, :3]  # first 3 columns
min_vals = cols_to_norm.min(axis=0)
max_vals = cols_to_norm.max(axis=0)

normalized = (cols_to_norm - min_vals) / (max_vals - min_vals)
print(normalized)    # normalise=(data-min) / (max-min)


[[0.52542373 0.75       0.71794872]
 [0.18644068 0.625      0.28205128]
 [0.28813559 0.45833333 0.32051282]
 [0.10169492 0.41666667 0.96153846]
 [0.38983051 0.70833333 0.83333333]
 [0.18644068 0.125      0.67948718]
 [0.79661017 0.125      0.20512821]
 [0.15254237 0.79166667 0.82051282]
 [0.22033898 0.83333333 0.71794872]
 [0.6779661  0.625      0.01282051]
 [0.06779661 0.58333333 0.62820513]
 [0.6779661  0.20833333 0.83333333]
 [0.89830508 0.20833333 1.        ]
 [0.47457627 1.         0.06410256]
 [0.         0.79166667 0.52564103]
 [0.77966102 0.25       0.26923077]
 [0.08474576 1.         0.24358974]
 [0.20338983 0.29166667 0.30769231]
 [0.49152542 0.20833333 0.67948718]
 [0.6779661  0.58333333 0.8974359 ]
 [0.83050847 0.29166667 0.91025641]
 [0.3220339  0.20833333 0.80769231]
 [0.79661017 0.16666667 0.79487179]
 [0.98305085 0.83333333 0.47435897]
 [0.13559322 0.95833333 0.56410256]
 [0.86440678 0.125      0.43589744]
 [0.49152542 0.625      0.30769231]
 [0.86440678 0.08333333 0.94