In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[7,8,9],[1,4,6]])
print(arr)

[[1 2 3]
 [7 8 9]
 [1 4 6]]


In [3]:
flat=arr.flatten()
print(flat)

[1 2 3 7 8 9 1 4 6]


In [7]:
print(flat[3])  #Indexing same as python
print(flat[-4])
print(flat[1])

7
9
2


In [9]:
print(flat[1:4])  # [2,3,7] (slice from index 1 to 3)
print(flat[:3])   # [1,2,3] (first 3 elements)
print(flat[::2])  # [1,3,8,1,6] (every 2nd element)  #(start:stop:jump)

[2 3 7]
[1 2 3]
[1 3 8 1 6]


## Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

Why does this happen?

Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [10]:
train=np.arange(1,46)
train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [12]:
a=train[3:7]

In [14]:
a[2]=10
a

array([ 4,  5, 10,  7])

In [15]:
train

array([ 1,  2,  3,  4,  5, 10,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [ ]:
# If you need copy , explicitly use .copy()

In [17]:
b=train[2:9].copy()
b


array([ 3,  4,  5, 10,  7,  8,  9])

In [18]:
b[4]=1000000

In [19]:
b

array([      3,       4,       5,      10, 1000000,       8,       9])

In [20]:
train

array([ 1,  2,  3,  4,  5, 10,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

# FANCY INDEXING

In [21]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


# MASKING

In [22]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
