In [1]:
import numpy as np

In [2]:
arr=np.array([1,3,4,2,5,5,4])  #[1,2,3,4,4,5,5]

In [4]:
print(np.mean(arr))  #Compute the mean (average) of an array.

3.4285714285714284


In [5]:
print(np.std(arr)) #Compute the standard deviation of an array.

1.3997084244475304


In [7]:
print(np.max(arr)) #Compute the maximum value of an array.
print(np.min(arr)) #Compute the minimum value of an array.

5
1


In [8]:
print(np.var(arr)) #Compute the variance of an array.

1.959183673469388


In [10]:
print(np.sum(arr)) 
print(np.prod(arr))

24
2400


In [12]:
print(np.median(arr)) # Compute the median of an array.

4.0


In [13]:
print(np.percentile(arr,95))  #Compute the percentile of an array.

5.0


In [14]:
print(np.argmin(arr))  #Return the index of the minimum value in an array.
print(np.argmax(arr))  #Return the index of the maximum value in an array.

0
4


In [18]:
arr2=np.array([12,43,55,65,43,45,0])

In [19]:
print(np.corrcoef(arr,arr2))

[[1.        0.1390222]
 [0.1390222 1.       ]]


In [20]:
print(np.unique(arr)) #Find the unique elements of an array.

[1 2 3 4 5]


In [21]:
print(np.diff(arr)) #np.diff() literally calculates the difference between consecutive elements in an array.

[ 2  1 -2  3  0 -1]


In [22]:
print(np.cumsum(arr)) #“Keep adding each number to the total so far, and show me the running score.” 🏆

[ 1  4  8 10 15 20 24]


In [23]:
print(np.log(arr))

[0.         1.09861229 1.38629436 0.69314718 1.60943791 1.60943791
 1.38629436]


In [24]:
print(np.exp(arr))

[  2.71828183  20.08553692  54.59815003   7.3890561  148.4131591
 148.4131591   54.59815003]


In [25]:
print(np.sqrt(arr))

[1.         1.73205081 2.         1.41421356 2.23606798 2.23606798
 2.        ]


In [28]:
print(np.vstack((arr,arr2))) # stacks arr and arr2 vertically

[[ 1  3  4  2  5  5  4]
 [12 43 55 65 43 45  0]]


In [29]:
print(np.hstack((arr,arr2))) # stacks arr and arr2 horizontally

[ 1  3  4  2  5  5  4 12 43 55 65 43 45  0]
