In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arrSum=np.sum(arr,axis=1)
arrSum

array([ 6, 15, 24])

In [8]:
arrSum.shape

(3,)

In [9]:
arrSum1=np.sum(arr,axis=0)
arrSum1

array([12, 15, 18])

In [10]:
arrSum1.shape

(3,)

In [13]:
print(arr[0][2])

3


In [14]:
print(arr[0,2])

3


In [16]:
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


# 3D ARRAYS

In [17]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [19]:
print(arr3D[1,1,2])

12
