# OPERATIONS ON ARRAYS

In [1]:
import numpy as np

### SLICING

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Sliced : ",a[2:7])
print("With step : ",a[1:9:2])
print("Negative indexing : ",a[-8:-3])

Sliced :  [3 4 5 6 7]
With step :  [2 4 6 8]
Negative indexing :  [5 6 7 8 9]


In [3]:
a_2d=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Slicing : ",a_2d[1,2])  #2nd column 1st row element
print("Slicing : ",a_2d[1])  #Entire 1st row
print("Slicing : ",a_2d[:,2]) #Entire 2nd column
print("Slicing : ",a_2d[0:1,1:2])




Slicing :  6
Slicing :  [4 5 6]
Slicing :  [3 6 9]
Slicing :  [[2]]


### SORTING

In [4]:
unsorted=np.array([1,3,2,4,6,4,45,67,89,65,-10000000000])
print("Sorted : ",np.sort(unsorted))

Sorted :  [-10000000000            1            2            3            4
            4            6           45           65           67
           89]


In [7]:
unsorted_2d=np.array([[1,3,2],
                      [5,99,87],
                      [0,85,9554456]])

print("Sorted column wise : ",np.sort(unsorted_2d,axis=0))
print("Sorted row wise : ",np.sort(unsorted_2d,axis=1))



Sorted column wise :  [[      0       3       2]
 [      1      85      87]
 [      5      99 9554456]]
Sorted row wise :  [[      1       2       3]
 [      5      87      99]
 [      0      85 9554456]]


### FILTER

In [13]:
numbers=np.arange(1,10000)
even_numbers=numbers[numbers%2==0]
print("Even numbers are : ",even_numbers)

Even numbers are :  [   2    4    6 ... 9994 9996 9998]


### FILTER WITH MASK

In [9]:
mask=numbers>9990
print("Numbers greater than 9990 are : ",numbers[mask])

Numbers greater than 9990 are :  [9991 9992 9993 9994 9995 9996 9997 9998 9999]


### FANCY INDEXING vs NP WHERE()

In [14]:
indices=[0,2,4]
print("By fancy indexing : ",numbers[indices])

where_result=np.where(numbers>9900)
print(where_result)
print(numbers[where_result])

By fancy indexing :  [1 3 5]
(array([9900, 9901, 9902, 9903, 9904, 9905, 9906, 9907, 9908, 9909, 9910,
       9911, 9912, 9913, 9914, 9915, 9916, 9917, 9918, 9919, 9920, 9921,
       9922, 9923, 9924, 9925, 9926, 9927, 9928, 9929, 9930, 9931, 9932,
       9933, 9934, 9935, 9936, 9937, 9938, 9939, 9940, 9941, 9942, 9943,
       9944, 9945, 9946, 9947, 9948, 9949, 9950, 9951, 9952, 9953, 9954,
       9955, 9956, 9957, 9958, 9959, 9960, 9961, 9962, 9963, 9964, 9965,
       9966, 9967, 9968, 9969, 9970, 9971, 9972, 9973, 9974, 9975, 9976,
       9977, 9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987,
       9988, 9989, 9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998]),)
[9901 9902 9903 9904 9905 9906 9907 9908 9909 9910 9911 9912 9913 9914
 9915 9916 9917 9918 9919 9920 9921 9922 9923 9924 9925 9926 9927 9928
 9929 9930 9931 9932 9933 9934 9935 9936 9937 9938 9939 9940 9941 9942
 9943 9944 9945 9946 9947 9948 9949 9950 9951 9952 9953 9954 9955 9956
 9957 9958 9959 9960 9961 

In [15]:
condition_array=np.where(numbers>9900,numbers*0,numbers*1)  # equivalent to retrun numbers*0 if numbers>9900 else numbers*1
print("The array with your condition is : ",condition_array)

The array with your condition is :  [1 2 3 ... 0 0 0]


In [16]:
condition_array=np.where(numbers>9900,True,False) 
print("The array with your condition is : ",condition_array)

The array with your condition is :  [False False False ...  True  True  True]


### ADDING AND REMOVING DATA


In [18]:
arr1=np.array([1,2,3,6,7,9])
arr2=np.array([2,4,3,5,8,9])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 6 7 9 2 4 3 5 8 9]


In [20]:
arr=np.array([1,2,5,4,6,7,8,7,6,100201202010201010])
new_arr=np.delete(arr,9)  #Deletes element at index 9 of arr
print(new_arr)

[1 2 5 4 6 7 8 7 6]


### ARRAY COMPATABILITY

In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("Cmpatibilty shapes : ",a.shape==b.shape)


Cmpatibilty shapes :  True


In [22]:
arr=np.array([[1,2],
              [3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((arr,new_row))

new_column=np.array([[7],[8]])  #Same dimension as on whom you are staking..

with_new_column=np.hstack((arr,new_column))

print(with_new_row)
print(with_new_column)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
