# Create a 3×3 array filled with random numbers and print its shape.

In [1]:
import numpy as np

In [11]:
arr1=np.random.randint(10, 20, size=(3, 4))  
# random ints from 10 (inclusive) to 20 (exclusive)


4

In [12]:
arr1.shape

(3, 4)

# Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [13]:
arr=np.array([1.1,2.2,3.3])
arr

array([1.1, 2.2, 3.3])

In [15]:
intarr=arr.astype('int32')
intarr

array([1, 2, 3], dtype=int32)

# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [16]:
arr=np.array([1,2,3,4,5,6])
idx=[1,3,5]
arr[idx]

array([2, 4, 6])

# Reshape a 1D array of size 9 into a 3×3 matrix.

In [20]:
arr=np.array([1,3,4,5,5,4,54,4,455444])
arr

array([     1,      3,      4,      5,      5,      4,     54,      4,
       455444])

In [21]:
reshaped=arr.reshape((3,3))
reshaped

array([[     1,      3,      4],
       [     5,      5,      4],
       [    54,      4, 455444]])

# Use boolean masking to filter numbers greater than 50 in an array.

In [22]:
arr=np.arange(1,1000)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [23]:
mask=arr>50
arr[mask]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
       168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,
       194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206,
       207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
       220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 23