In [2]:
import numpy as np
import time

In [6]:
# PYTHON

size=1_000_092

l1=list(range(size))
l2=list(range(size))

start=time.time()
add = [x+y for x,y in zip(l1,l2)]
end=time.time()

print(add)
print("Time taken by python is : ",end-start)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [7]:
# NUMPY

size=1_000_092

array1=np.array(l1)
array2=np.array(l2)

start=time.time()
add=array1+array2  
end=time.time()

print(add)
print("Time taken by numpy is : ",end-start)

[      0       2       4 ... 2000178 2000180 2000182]
Time taken by numpy is :  0.0223543643951416


# CREATING ARRAYS

In [8]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [9]:
#  NumPy stores data in a contiguous memory block, making access faster than lists.🔹 shape shows the dimensions of an array.

# Memory Efficiency – NumPy vs. Lists

In [10]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


# Vectorization – No More Loops!

In [12]:
# Python list (loop-based)
list_squares = [x ** 2 for x in l1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2